server:
  port: 8000

spring:
  application:
    name: jwt-server
  messages:
    basename: org/hibernate/validator/ValidationMessages, messages/ErrorMessages

logging:
  level:
    ROOT: INFO

jwt:
  secret: a6e21884876f43819523c31033fa697e

logbook:
  format.style: http
  write:
    level: DEBUG
    category: http.wire-log

---
    
spring:
  datasource:
    url: jdbc:oracle:thin:@//192.168.99.103:1521/xe
    username: safe_user
    password: 1234qwer
    driver-class-name: oracle.jdbc.OracleDriver

#hibernate config

  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
server:
  port: 4000
