server:
  port: 4000 


spring:
  datasource:
    url: jdbc:oracle:thin:@//127.0.0.1:49161/xe
    username: safe_user
    password: 1234qwer
    driver-class-name: oracle.jdbc.OracleDriver
    #hibernate config

  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true

  application:
    name: jwt-server
  messages:
    basename: org/hibernate/validator/ValidationMessages, messages/ErrorMessages

## MULTIPART (MultipartProperties)
# Enable multipart uploads
  http:
    multipart:
      max-file-size: 3MB
      max-request-size: 4MB
  servlet:
    multipart:
      enabled: true
# Threshold after which files are written to disk.
      file-size-threshold: 2KB
# Max file size.
      max-file-size: 200MB
# Max Request Size
      max-request-size: 215MB
     
  mvc:
    contentnegotiation:
      favor-parameter: true
      media-types:
        pdf: application/pdf

## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file:
  upload-dir: ./uploads

logging:
  level:
    ROOT: INFO

jwt:
  secret: a6e21884876f43819523c31033fa697e

logbook:
  format.style: http
  write:
    level: DEBUG
    category: http.wire-log


  
